name: Deploy FastAPI App via Self-Hosted Runner

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted  # Self-hosted GitHub runner
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Create .env file from GitHub Secrets
        run: |
          echo "${{ secrets.DOCKER_ENV_FILE }}" > /home/jazzam/actions-runner/jazzaam-nodejs/.env
          echo ".env file created successfully."


      - name: Build Docker Image
        run: |
          echo "Building latest Docker image..."
          sudo docker build --no-cache -t mdm-nodejs-image .

      - name: Stop & Remove Existing Container
        run: |
          CONTAINER_ID=$(sudo docker ps -aq --filter "name=mdm-nodejs-container")
          if [ ! -z "$CONTAINER_ID" ]; then
            sudo docker stop mdm-nodejs-container
            sudo docker rm mdm-nodejs-container
          fi

      - name: Run New Container from Latest Image
        run: |
          echo "Running container from latest image..."
          sudo docker run -d --name mdm-nodejs-container -p 3013:3000 mdm-nodejs-image

      - name: Cleanup Unused Docker Images
        run: |
          echo "Cleaning up old Docker images..."
          sudo docker image prune -af

  nginx:
    runs-on: self-hosted
    needs: deploy
    steps:
      - name: Test and Reload Nginx
        run: |
          echo "Testing nginx configuration..."
          sudo nginx -t && sudo systemctl restart nginx
